### PR TITLE
doc: propose lifecycles

### PR DESCRIPTION
**Pull request by chrisdickinson**
This modifies the README to list the stages that this WG will operate in, and moves the proposed topics of discussion to the issue tracker.

### CODE REVIEW

**Comment by petkaantonov** [comment]
LGTM

**Comment by benjamingr** [comment]
Are we sure we want to remove the topics list? I think it's pretty inviting and focuses this WG on more than just the pr of promises into core.

**Comment by petkaantonov** [comment]
Isn't there an issue for each topic already?

**Comment by chrisdickinson** [comment]
@benjamingr I think the topics list should be captured in issues; enumerating the topics we wish to talk about in the README sort of bounds the set, vs. stating what we're concerned about at each stage and letting the issue tracker reflect that.

**Comment by chrisdickinson** [comment]
Merging this now so that the present state of the WG is well-reflected — will capture topic list as issues as they come up!

**Pull request merged**
